// 統一管理所有事件名稱
export const GameEvent = {
    PLAYER_HP_CHANGED: "PLAYER_HP_CHANGED",
    PLAYER_EXP_CHANGED: "PLAYER_EXP_CHANGED",
    PLAYER_DIED: "PLAYER_DIED",
    SCORE_CHANGED: "SCORE_CHANGED",
    GAME_PAUSED: "GAME_PAUSED",
    GAME_RESUMED: "GAME_RESUMED",
    SAVE_LOADED: "SAVE_LOADED",
    LEADERBOARD_UPDATED: "LEADERBOARD_UPDATED",
    NPC_MOCKED: "NPC_MOCKED",
    NPC_DIED: "NPC_DIED",
    COMBAT_HIT_CONFIRMED: "COMBAT_HIT_CONFIRMED",
    ITEM_COLLECTED: "ITEM_COLLECTED",
    MERCHANT_PURCHASED: "MERCHANT_PURCHASED",
    SPAWN_ITEM: "SPAWN_ITEM",
    PORTAL_USED: "PORTAL_USED",
    BOUNCE_PAD_TRIGGERED: "BOUNCE_PAD_TRIGGERED",
    REALTIME_STATE_UPDATED: "REALTIME_STATE_UPDATED",
    PLAYER_TOOL_CHANGED: "PLAYER_TOOL_CHANGED",
    JETPACK_FUEL_CHANGED: "JETPACK_FUEL_CHANGED",
    GRAPPLE_ATTACHED: "GRAPPLE_ATTACHED",
    GRAPPLE_DETACHED: "GRAPPLE_DETACHED",
    BOSS_PHASE_CHANGED: "BOSS_PHASE_CHANGED",
    BOSS_DEFEATED: "BOSS_DEFEATED",
    BOSS_SUMMONED_MINION: "BOSS_SUMMONED_MINION",
    PLAYER_WATER_STATE_CHANGED: "PLAYER_WATER_STATE_CHANGED",
    VEHICLE_ENTERED: "VEHICLE_ENTERED",
    VEHICLE_EXITED: "VEHICLE_EXITED",
    THEME_CHANGED: "THEME_CHANGED",
    MAP_GENERATION_PROGRESS: "MAP_GENERATION_PROGRESS",
    MAP_GENERATION_UPDATED: "MAP_GENERATION_UPDATED"
};

// 實體類型
export enum EntityType {
    PLAYER = 0,
    NPC_PEACE = 1,
    NPC_NEUTRAL = 2,
    NPC_HOSTILE = 3
}

cc.Enum(EntityType);
